/* eslint-disable */
namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_BEANSTALK_SERVER_URL: string;
    NEXT_PUBLIC_SCAN_MUMBAI_KEY: string;
    NEXT_PUBLIC_SCAN_POLYGON_KEY: string;
    NEXT_PUBLIC_SCAN_ETHEREUM_KEY: string;
    NEXT_PUBLIC_SCAN_GOERLI_KEY: string;
    NEXT_PUBLIC_SCAN_SEPOLIA_KEY: string;
    NEXT_PUBLIC_SCAN_AVALANCHE_KEY: string;
    NEXT_PUBLIC_SCAN_FUJI_KEY: string;
    NEXT_PUBLIC_SCAN_ARBITRUM_KEY: string;
    NEXT_PUBLIC_SCAN_ARBITRUM_GOERLI_KEY: string;
    NEXT_PUBLIC_SCAN_OPTIMISM_KEY: string;
    NEXT_PUBLIC_SCAN_OPTIMISM_GOERLI_KEY: string;
    ALCHEMY_API_KEY: string;
  }
}
