/* eslint-disable */
namespace NodeJS {
  interface ProcessEnv {
    ALCHEMY_ETHEREUM_KEY: string;
    ALCHEMY_GOERLI_KEY: string;
    ALCHEMY_POLYGON_KEY: string;
    ALCHEMY_MUMBAI_KEY: string;
    ALCHEMY_AVALANCHE_KEY: string;
    ALCHEMY_FUJI_KEY: string;
    ALCHEMY_OPTIMISM_KEY: string;
    ALCHEMY_OPTIMISM_GOERLI_KEY: string;
    NEXT_PUBLIC_BEANSTALK_SERVER_URL: string;
    NEXT_PUBLIC_SCAN_ETHEREUM_KEY: string;
    NEXT_PUBLIC_SCAN_GOERLI_KEY: string;
    NEXT_PUBLIC_SCAN_SEPOLIA_KEY: string;
    NEXT_PUBLIC_SCAN_POLYGON_KEY: string;
    NEXT_PUBLIC_SCAN_MUMBAI_KEY: string;
    NEXT_PUBLIC_SCAN_AVALANCHE_KEY: string;
    NEXT_PUBLIC_SCAN_FUJI_KEY: string;
    NEXT_PUBLIC_SCAN_OPTIMISM_KEY: string;
    NEXT_PUBLIC_SCAN_OPTIMISM_GOERLI_KEY: string;
  }
}
